"""initial MPLADS schema

Revision ID: 67e204cdc0f8
Revises: 
Create Date: 2026-09-22 23:30:48.077519
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67e204cdc0f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
